
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      serviceAccountName: aws-dynamo
      containers:
      - name: order
        image: izaakdale/service-order
        env: 
        - name: SERVICE_ADDRESS
          value: "80"
        - name: SERVICE_DYNAMOTABLENAME
          value: "ordering-app"
        - name: SERVICE_DYNAMOREGION
          value: "eu-west-2"
        - name: SERVICE_GRPCADDRESS
          value: "172.20.142.32:50001"
        ports:
        - name: web
          containerPort: 80
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
          limits:
            memory: 256Mi
            cpu: 250m
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - general
      tolerations:
      - operator: Exists
        effect: NoSchedule
      # tolerations:
      # - key: team
      #   operator: Equal
      #   value: devops
      #   effect: NoSchedule